### ISSUE TITLE
Requesting location numerous times

### ISSUE THREAD

**Issue by AndrewLieberman** [nschultz14/Stuur#34]
When location services are disabled, Stuur requests to enable them three successive times (assuming positive answers).

**Comment by nschultz14** [comment]
this is similar to issue #17 but I'm not sure if its the same so we can leave them both open for now

**Comment by evanradcliffe** [comment]
This might be fixed, need to debug on Lou's phone @alphalfa on github

**Comment by alphalfa** [comment]
Want to comment, my phone requests location permission even with location services on. Global and friend tabs work (despite asking multiple times for permission). Local may not.

**Comment by evanradcliffe** [comment]
fixed in https://github.com/nschultz14/Stuur/commit/60956db76b25ae745d8dfe5da036790dfe540c8b
