### ISSUE TITLE
Emoji's received as question marks

### ISSUE THREAD

**Issue by beefy** [nschultz14/Stuur#7]
I posted the details here: http://stackoverflow.com/questions/35946052/trouble-encoding-emojis-for-web-service-in-android

If you use the request URL directly, and add an extra \ before the \u, it gets correctly sent.
I tried doing something with regular expressions to parse out the emojis and then rejoin them, but that didn't work.  

One solution might be to send messages as a JSON instead of as URL parameters.

**Comment by evanradcliffe** [comment]
every character is now converted to Unicode before sending to the web server, commit https://github.com/nschultz14/Stuur/commit/f1f03a5bc5ae2be2c3f13c5e5d33b9efe478b87d

in collaboration with @nschultz14
